'NIA, nom i cognoms de l’alumne que ha fet més matrícules.'

SELECT M.NIA_ALUMNE, A.NOM, A.COGNOMS, COUNT(*) AS MATRICULES
FROM MATRICULACIO M
JOIN ALUMNES A
ON M.NIA_ALUMNE = A.NIA
GROUP BY M.NIA_ALUMNE, A.NOM, A.COGNOMS
HAVING COUNT(*) >= ALL(
SELECT COUNT(*)
FROM MATRICULACIO M
GROUP BY M.NIA_ALUMNE
)