'Codi i nom del departament amb menys professors'

SELECT P.CODI_DEPARTAMENT, D.NOM
FROM PROFESSORS P
JOIN DEPARTAMENTS D
ON D.CODI = P.CODI_DEPARTAMENT
GROUP  BY P.CODI_DEPARTAMENT, D.NOM
HAVING COUNT(*) <= ALL(SELECT COUNT(*) FROM PROFESSORS P GROUP BY P.CODI_DEPARTAMENT)
