SELECT DISTINCT P.NOM, P.COGNOMS, D.TIPUS_DOCENCIA
FROM DOCENCIA D
JOIN PROFESSORS P ON D.NIA_PROFESSOR = P.NIA
WHERE D.CODI_ASSIGNATURA = (SELECT CODI FROM ASSIGNATURES WHERE NOM = 'Bases de Dades Relacionals');