SELECT DISTINCT D.NIA_PROFESSOR AS NIA, (SELECT P.NOM FROM PROFESSORS P WHERE P.NIA = D.NIA_PROFESSOR) AS NOM, (SELECT P.COGNOMS FROM PROFESSORS P WHERE P.NIA = D.NIA_PROFESSOR) AS COGNOMS
FROM DOCENCIA D
JOIN CLASSES C
ON D.CODI_ASSIGNATURA = C.CODI_ASSIGNATURA
AND D.TIPUS_DOCENCIA = C.TIPUS_DOCENCIA
AND D.GRUP = C.GRUP
WHERE C.CODI_AULA = 'Q1/1011'
ORDER BY NIA