SELECT DISTINCT C.CODI_ASSIGNATURA AS CODI, (SELECT A.NOM FROM ASSIGNATURES A WHERE A.CODI = C.CODI_ASSIGNATURA) AS NOM
FROM CLASSES C
WHERE C.CODI_AULA LIKE 'Q2/%'
GROUP BY C.CODI_ASSIGNATURA
HAVING COUNT(C.GRUP)