SELECT P.NOM, P.COGNOMS, (SELECT NOM FROM ASSIGNATURES WHERE CODI = D.CODI_ASSIGNATURA), D.GRUP
FROM PROFESSORS P
JOIN DOCENCIA D ON P.NIA = D.NIA_PROFESSOR
WHERE
    P.CATEGORIA = 'Ajudant'
    AND P.CODI_DEPARTAMENT = (SELECT CODI FROM DEPARTAMENTS WHERE NOM = 'Ciències de la Computació')
    AND D.TIPUS_DOCENCIA = 'Teoria'