SELECT CURS, CONVOCATORIA_1, CONVOCATORIA_2
FROM MATRICULACIO
WHERE
    NIA_ALUMNE = (SELECT NIA FROM ALUMNES WHERE NOM = 'Yordi' AND COGNOMS = 'Poveda')
    AND CODI_ASSIGNATURA = (SELECT CODI FROM ASSIGNATURES WHERE NOM = 'Bases de Dades Relacionals')
ORDER BY CURS

/*
SELECT M.CURS, M.CONVOCATORIA_1, M.CONVOCATORIA_2
FROM MATRICULACIO M
INNER JOIN ALUMNES A ON M.NIA_ALUMNE = A.NIA
INNER JOIN ASSIGNATURES ASG ON M.CODI_ASSIGNATURA = ASG.CODI
WHERE A.NOM = 'Yordi' AND A.COGNOMS = 'Poveda'
  AND ASG.NOM = 'Bases de Dades Relacionals'
ORDER BY M.CURS;
*/