SELECT MIN(A.CAPACITAT) AS MINIM, MAX(A.CAPACITAT) AS MAXIM, AVG(A.CAPACITAT) AS MITJA, SUM(A.CAPACITAT) AS TOTAL
FROM AULES A
JOIN CLASSES C ON A.CODI = C.CODI_AULA
WHERE
    C.CODI_ASSIGNATURA = (SELECT CODI FROM ASSIGNATURES WHERE NOM = 'Bases de Dades No Relacionals')