SELECT A.NOM, M.CURS, M.CONVOCATORIA_1 AS C_1, M.CONVOCATORIA_2 AS C_2
FROM MATRICULACIO M
JOIN ASSIGNATURES A ON M.CODI_ASSIGNATURA = A.CODI 
WHERE
    NIA_ALUMNE = (SELECT NIA FROM ALUMNES WHERE NOM = 'Jaume' AND COGNOMS LIKE 'Camps%')
ORDER BY A.NOM, M.CURS