SELECT DISTINCT A.CODI, A.NOM
FROM ASSIGNATURES A
JOIN CLASSES C ON A.CODI = C.CODI_ASSIGNATURA
WHERE C.CODI_AULA IN
(
    SELECT CODI_AULA FROM CLASSES WHERE CODI_ASSIGNATURA =
    (
        SELECT CODI FROM ASSIGNATURES WHERE NOM = 'Bases de Dades Relacionals'
    )
)
AND A.CODI != (SELECT CODI FROM ASSIGNATURES WHERE NOM = 'Bases de Dades Relacionals')