SELECT (SELECT A.NOM FROM ASSIGNATURES A WHERE A.CODI = D.CODI_ASSIGNATURA) AS ASSIGNATURA, COUNT(DISTINCT P.CODI_DEPARTAMENT) AS NUM_DEP
FROM DOCENCIA D
JOIN PROFESSORS P
ON D.NIA_PROFESSOR = P.NIA
GROUP BY D.CODI_ASSIGNATURA
HAVING COUNT(DISTINCT P.CODI_DEPARTAMENT) > 1
ORDER BY ASSIGNATURA