SELECT (SELECT A.NOM FROM ALUMNES A WHERE A.NIA = M.NIA_ALUMNE) AS NOM, (SELECT A.COGNOMS FROM ALUMNES A WHERE A.NIA = M.NIA_ALUMNE) AS COGNOMS
FROM MATRICULACIO M
WHERE M.CODI_ASSIGNATURA = (SELECT A.CODI FROM ASSIGNATURES A WHERE A.NOM = 'Bases de Dades Relacionals')
GROUP BY M.NIA_ALUMNE
HAVING COUNT(M.CODI_ASSIGNATURA) > 1
ORDER BY COGNOMS