SELECT 
    COUNT(NIA_ALUMNE) AS TOTAL_MATRICULATS, 
    COUNT(DISTINCT GRUP) AS TOTAL_GRUPS,
    COUNT(NIA_ALUMNE) / COUNT(DISTINCT GRUP) AS PROMIG
FROM MATRICULACIO
WHERE CODI_ASSIGNATURA = (SELECT CODI FROM ASSIGNATURES WHERE NOM = 'Bases de Dades Relacionals') 
  AND CURS = '2022-23'