SELECT M.CONVOCATORIA_1 AS NOTA, COUNT(*) AS NUM_ALUMNES
FROM MATRICULACIO M
WHERE M.CURS = '2021-22'
AND M.CODI_ASSIGNATURA = (SELECT A.CODI FROM ASSIGNATURES A WHERE A.NOM = 'Bases de Dades Relacionals')
GROUP BY M.CONVOCATORIA_1
ORDER BY NOTA