'Nom i codi de l’assignatura amb el nombre d’alumnes matriculats més gran.
Atributs de sortida: Codi i nom de l’assignatura, nombre d’alumnes.'

SELECT M.CODI_ASSIGNATURA AS CODI, A.NOM, COUNT(DISTINCT M.NIA_ALUMNE)
FROM MATRICULACIO M
JOIN ASSIGNATURES A
ON A.CODI = M.CODI_ASSIGNATURA
GROUP BY M.CODI_ASSIGNATURA, A.NOM
HAVING COUNT(DISTINCT M.NIA_ALUMNE) >= ALL
(
    SELECT COUNT(DISTINCT M.NIA_ALUMNE) FROM MATRICULACIO M GROUP BY M.CODI_ASSIGNATURA
)