SELECT CODI_ASSIGNATURA, GRUP, COUNT(*)
FROM MATRICULACIO
WHERE CODI_ASSIGNATURA BETWEEN 104350 AND 104370
AND CURS = '2021-22'
AND (CONVOCATORIA_1 > 1)
GROUP BY CODI_ASSIGNATURA, GRUP
ORDER BY CODI_ASSIGNATURA, GRUP