"Codi i nom del departament amb més professors"

SELECT P.CODI_DEPARTAMENT, (SELECT D.NOM FROM DEPARTAMENTS D WHERE D.CODI = P.CODI_DEPARTAMENT) AS NOM, COUNT(*) AS NUM_PROFESSORS
FROM PROFESSORS P
GROUP BY P.CODI_DEPARTAMENT
HAVING COUNT(*) >= ALL
(SELECT COUNT(*)
FROM PROFESSORS P
GROUP BY P.CODI_DEPARTAMENT)